[tool.poetry]
name = "aiospamc"
version = "0.4.1"
description = "An asyncio-based library to communicate with SpamAssasin's SPAMD service."
authors = ["Michael Caley <mjcaley@darkarctic.com>"]
license = "MIT"
readme = "README.rst"

repository = "https://github.com/mjcaley/aiospamc"
homepage = "https://github.com/mjcaley/aiospamc"

classifiers = [
    'Development Status :: 4 - Beta',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Intended Audience :: Developers',
    'Intended Audience :: System Administrators',
    'License :: OSI Approved :: MIT License',
    'Topic :: Communications :: Email :: Filters'
]

keywords = ["spam", "spamc", "spamassassin"]

[tool.poetry.dependencies]
python = "^3.5"
sphinx = { version="^1.6.2", optional=true }
sphinxcontrib-asyncio = { version="^0.2.0", optional=true }

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.9.0"
asynctest = "^0.12.2"
pytest-cov = "^2.6"
pytest = "^3.0"

[tool.poetry.extras]
docs = ["sphinx", "sphinxcontrib-asyncio"]

[tool.poetry.scripts]
test = 'pytest:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
